version: "3"
services:
  golang:
    build:
      context: ./conf/go
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 443:3000
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./..:/var/www
    network_mode: bridge

  postgres:
    image: postgres
    user: root
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    network_mode: bridge