version: "3"
services:
  php_base:
    build:
      context: ./conf/php
      dockerfile: Dockerfile
    restart: always
    tty: true
    user: ${UID}:${GID}
    volumes:
      - ./..:/var/www
      - ~/.composer:/var/www/.composer
    network_mode: bridge
    environment:
      # client_host=172.17.0.1 for linux
      # client_host=host.docker.internal for windows
      XDEBUG_CONFIG: client_host=host.docker.internal
      REDIS_PORT: 6379
