version: "3"
services:
  php:
    extends:
      file: php.yml
      service: php_base
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./data/tmp:/tmp

  mysql:
    image: library/mysql
    user: "${UID}:${GID}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    network_mode: bridge